// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 9/26/2026, 7:29:01 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/marquis/erranders/barter-app/barter-admin/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/marquis/erranders/barter-app/barter-admin/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/marquis/erranders/barter-app/barter-admin/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/marquis/erranders/barter-app/barter-admin/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/marquis/erranders/barter-app/barter-admin/plugins/**/*.{js,ts,mjs}","/Users/marquis/erranders/barter-app/barter-admin/composables/**/*.{js,ts,mjs}","/Users/marquis/erranders/barter-app/barter-admin/utils/**/*.{js,ts,mjs}","/Users/marquis/erranders/barter-app/barter-admin/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/marquis/erranders/barter-app/barter-admin/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/marquis/erranders/barter-app/barter-admin/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/marquis/erranders/barter-app/barter-admin/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;